server:
  port: 9000  # 9000? ??? ??

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cfxek62xmnz9.ap-northeast-2.rds.amazonaws.com:3306/hackaton_schema
    username: admin
    password: greenquest

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        diarect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
